server:
  port: 8080

spring:
  application:
    name: funkomania-api

  # Configuración para habilitar Problem Details en las respuestas de error
  mvc:
    problemdetails:
      enabled: true

  # Configuración Spring Data JPA
  datasource:
    url: ${SPRING_DATASOURCE_URL_DOCKER}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # - none: No se realizará ninguna acción sobre la base de datos. Se asume que la estructura ya está creada.
      # - create-drop: Crea la estructura de la base de datos al iniciar la aplicación y la elimina al detenerla.
      # - validate: Valida que la estructura de la base de datos coincida con las entidades, pero no realiza cambios.
      ddl-auto: validate
      # Configuración para mostrar las consultas SQL generadas por Hibernate en la consola.
      naming:
        # Desactiva la conversión automática de nombres (para evitar problemas con mayúsculas y minúsculas en MySQL).
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    show-sql: true # Muestra las consultas SQL generadas por Hibernate en la consola.

# Configuración JWT
jwt:
  secret: ${JWT_SECRET} # Clave secreta para firmar los tokens JWT, se debe configurar en las variables de entorno.
  expiration: 3600000 # Tiempo de expiración del token en milisegundos (1 hora).